branches:
  only:
  - /.*/

matrix:
  include:
    - language: python
      python:
        - "2.7"
    - language: node_js
    node_js:
      - "lts/*"

addons:
  postgresql: "11.1"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433

before_script:
  - sudo sh -c 'echo "local all all trust" > /etc/postgresql/11/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/11/main/pg_hba.conf'
  - sudo service postgresql restart
  - psql -c 'CREATE DATABASE randomizer;' -U postgres
  - psql -U postgres randomizer < ./database/exportSql.sql

script :
  - npm install
  - npm test

notifications:
    email: false
