language: node_js
node_js:
 - "lts/*"

services:
  - postgresql

addons:
  postgresql: "11.1"

before_script:
  #- sudo /etc/init.d/postgresql stop
  #- pg_ctl stop
  #- killall postgresqld
  # - ps ux | grep postgres*
  # - sudo apt-get install curl ca-certificates
  # - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  # - sudo touch /etc/apt/sources.list.d/pgdg.list
  # - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  # - sudo apt-get update
  # - sudo apt-get -f install postgresql-11 #postgres-client-11
  # - sudo /etc/init.d/postgresql stop
  # - /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/11/main -l logfile start
  - psql -c 'CREATE EXTENSION postgres_fdw;' -U postgres
  - psql -c 'CREATE SERVER randomizerServerCI FOREIGN DATA WRAPPER postgres_fdw;' -U postgres
  - psql -c 'CREATE DATABASE randomizerTestCI;' -U postgres
  - psql -U postgres randomizerTestCI < ./backup_DB/exportSql.sql

script :
  - npm install
  - npm app.js
  - npm test
