language: node_js
node_js:
 - "lts/*"

services:
  - postgresql

addons:
  postgresql: "11.1"

before_script:
  - psql -c 'CREATE DATABASE randomizerTestCI;' -U postgres
  - psql -U postgres randomizerTestCI < ./backup_DB/exportSql.sql

script :
  - npm install
  - npm app.js
  - npm test
