language: node_js
node_js:
 - "lts/*"

services:
  - postgresql

addons:
  postgresql: "11.1"

before_script:
  #- sudo /etc/init.d/postgresql stop
  #- pg_ctl stop
  #- killall postgresqld
  #- ps ux | grep postgres*
  # - sudo apt-get install curl ca-certificates
  # - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  # - sudo touch /etc/apt/sources.list.d/pgdg.list
  # - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  # - sudo apt-get update
  # - sudo /etc/init.d/postgresql stop
  # - sudo pg_ctlcluster 9.2 main stop
  # - sudo apt-get -f install postgresql-11 #postgres-client-11
  # - /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/11/main -l logfile start
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql*
  - sudo apt-get -y autoremove
  #- travis_retry sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 11" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-11 postgresql-client-11
  - sudo sh -c 'echo "local all postgres peer" > /etc/postgresql/11/main/pg_hba.conf'
  # - sudo sh -c 'echo "local all all trust" >> /etc/postgresql/11/main/pg_hba.conf'
  # - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/11/main/pg_hba.conf'
  #- sudo /etc/init.d/postgresql restart
  #- sudo service postgres restart 11
  - psql -c 'CREATE EXTENSION postgres_fdw;' -U postgres
  - psql -c 'CREATE SERVER randomizerServerCI FOREIGN DATA WRAPPER postgres_fdw;' -U postgres
  - psql -c 'CREATE DATABASE randomizerTestCI;' -U postgres
  - psql -U postgres randomizerTestCI < ./backup_DB/exportSql.sql

script :
  - npm install
  - npm app.js
  - npm test
