branches:
  only:
  - /.*/

language: node_js
node_js:
  - "lts/*"

before_install:
- sudo /etc/init.d/postgresql stop
- sudo apt-get -y remove --purge postgresql*
- sudo apt-get -y autoremove
- sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 11" >> /etc/apt/sources.list.d/postgresql.list'
- sudo apt-get update
- sudo apt-get -y install postgresql-11 postgresql-client-11

- sudo service postgresql restart 11.1
- psql -c 'CREATE EXTENSION postgres_fdw;' -U postgres
- psql -c 'CREATE SERVER randomizerServerCI FOREIGN DATA WRAPPER postgres_fdw;' -U postgres
- psql -c 'CREATE DATABASE randomizer;' -U postgres
- psql -U postgres randomizer < ./database/exportSql.sql

script :
  - npm install
  - npm test
